<H1 style="font-size:50px">7: Numerical Python (NumPy)</H1>

<div style = "width:95%; padding:5px 10px 5px;  margin:50px 0px 10px 10px; font-size:18px">
<UL>
    <LI> L'array: la struttura base di Numpy
    <LI> Come operare su interi array con un singolo comando
    <LI> Funzioni che agiscono su tutto un array
    <LI> Come selezionare gli elementi di un array che soddisfano una condizione
    <LI> Array a due dimensioni: le matrici
    <LI> L'algebra lineare
    <LI> Array multidimensionali
    <LI> Come vettorializzare una funzione scalare
    <LI> Leggere e scrivere array su un file di testo
</UL>
</div>

<hr>


## 7.1 Introduzione

Il linguaggio Python di base (incluse le librerie standard) fornisce strumenti sufficienti per completare semplici progetti computazionali. Tuttavia, esistono librerie Python dedicate che forniscono funzionalità estese che

-   forniscono strumenti numerici per automatizzare operazioni ricorrenti

-   sono semplici da usare

-   sono più efficienti in termini di tempo di CPU e di esigenze di memoria degli strumenti in Python base.

Citiamo tre librerie in particolare:

-   Il modulo `numpy`, introdotto in 07_numpy, che fornisce strumenti numerici. Numpy contiene fra le altre cose molte funzioni per manipolazioni statistiche che vengono presentate in 09_numpy_statistics.

-   Il modulo `matplotlib`, introdotto in 08_plots, che permette di creare grafici.

-   Il modulo `scipy` (SCIentific PYthon), introdotto in 10_scipy, che fornisce un gran numero di algoritmi numerici.

Molti degli algoritmi numerici resi disponibili da `numpy` e `scipy` sono forniti da librerie compilate, di solida tradizione, che spesso sono scritte in Fortran o C. Vengono quindi eseguite molto più velocemente di codice scritto in puro Python (che è interpretato). Generalmente, un codice compilato è due ordini di grandezza più veloce di un codice in puro Python.

Come al solito, si può utilizzare la funzione `help` su ciascuno dei metodi numerici per accedere alla documentazione.

## 7.2 Numpy e gli array

La librery NumPy (NUMerical PYthon) fornisce un nuovo tipo di struttura dei dati chiamata `array`s che permette di eseguire in modo efficiente operazioni su vettori e matrici. Fornisce inoltre diverse  operazioni legate all'algebra lineare (come risolvere sistemi di equazioni lineari, calcolo di autovettori e autovalori). Viene tradizionalmente importata come `np`.<BR>

NumPy introduce un nuovo tipo di dati detto “`array`”. Un array *sembra* molto simile a una lista ma può contenere solo elementi di un singolo tipo (mentre una lista può contenere oggetti di tipo diverso). Questo significa che gli array possono essere scritti in memoria in modo più efficiente. Gli array sono la struttura di dati migliore per i calcoli numerici in cui spesso si ha a che fare con vettori e matrici di tipo omogeneo.

Vettori, matrici bidimensionali e matrici con più di due indici sono tutti chiamati “arrays” in NumPy.

### 7.2.1 Vettor1 (1d-arrays)

La struttura dati data che useremo più spesso è il vettore. Qualche esempio di come crearne uno:

-   Conversione di una lista (o tuple) in un array usando <span>`numpy.array`</span>:

In [2]:
import numpy as np
x = np.array([0, 0.5, 1, 1.5])
print(x)

[0.  0.5 1.  1.5]


In [4]:
type(x)

numpy.ndarray

In [5]:
type([0, 0.5, 1, 1.5])

list

In [6]:
x

array([0. , 0.5, 1. , 1.5])

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#ff0000; margin:20px 0px 10px 10px">
    <h4> Attenzione!</h4>
    Notate come la rappresentazione sullo schermo di un array sia diversa se si invoca semplicemente il corrispondente simbolo oppure se si chiama la funzione <b>print</b>. La differenza è legata a due diverse funzioni intrinseche __str__ e __repr__ che possono essere utilizzate nella definizioni di <b>Classi</b>, di cui non parleremo nel corso.
</div>

- Creazione di un vettore usando "arange":

In [7]:
x = np.arange(0, 2, 0.5)
print(x)

[0.  0.5 1.  1.5]


-   Creazione di un vettore di zeri, di uno

In [8]:
x = np.zeros(4)
print(x)
y = np.ones(10)
print(y)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### I comandi linspace() e logspace()

In Numpy esiste il comando `linspace(x0, x1, n)`, che genera una lista di `n` elementi equidistanti fra `x0` e `x1` (inclusi). Il comando `logspace(x0, x1, n)` genera una lista di `n` elementi equidistanti, in scala logaritmica, fra `10\*\*x0` e `10\*\*x1`; è utile per fare plot logaritmici come vedremo in 08_plots. Alcuni esempi:

In [9]:
np.linspace(0,10,1001)

array([ 0.  ,  0.01,  0.02, ...,  9.98,  9.99, 10.  ])

In [10]:
np.linspace(-1,1,21)

array([-1. , -0.9, -0.8, -0.7, -0.6, -0.5, -0.4, -0.3, -0.2, -0.1,  0. ,
        0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

Ricordate che i primi due argomenti di logspace sono i logaritmi in base 10 del punto iniziale e di quello finale.

In [15]:
np.logspace(1,4,4)
#np.logspace(1.7,4.4,40)

array([   10.,   100.,  1000., 10000.])

#### Come scegliere o modificare il `tipo` di dati di un array

Quando viene creato un array è possibile specificare il tipo di dati che contiene. I tipi possibili sono: 'float', 'complex', 'int', 'bool', 'str' and 'object'. Un controllo più fine si può avere usando espressioni come 'float32', 'float64', 'int8', 'int16' oppure 'int32'; l'intero specifica il numero di bytes. 

In [21]:
array_f = np.array([1,2,3.14], dtype=float)
array_i = np.array([1.,2.24,3], dtype='int16')

In [17]:
array_f

array([1.  , 2.  , 3.14])

In [22]:
array_i

array([1, 2, 3], dtype=int16)

In [23]:
np.array([1,2,123456790],dtype='int32')

array([        1,         2, 123456790])

In [24]:
np.arange(1.3,2.2,0.1,dtype=complex)

array([1.3+0.j, 1.4+0.j, 1.5+0.j, 1.6+0.j, 1.7+0.j, 1.8+0.j, 1.9+0.j,
       2. +0.j, 2.1+0.j])

Il tipo di un array può essere modificato con il metodo astype

In [25]:
array_f.astype(complex)

array([1.  +0.j, 2.  +0.j, 3.14+0.j])

In [26]:
array_f.astype('int16')

array([1, 2, 3], dtype=int16)

### 7.2.2 Operazioni su array

- Una volta che l'array esiste, possiamo definire e recuperare il valore degli elementi. Per esempio:

In [27]:
x = np.zeros(4)
x[0] = 3.4
x[2] = 4
print(x)

[3.4 0.  4.  0. ]


- I metodi di slicing per le stringhe/liste/ntuple si possono applicare anche agli array:

In [28]:
print(x[0])
print(x[0:-1])

3.4
[3.4 0.  4. ]


- La lunghezza di un array si ottiene con `len`

In [29]:
len(x)

4

- Quando abbiamo un array possiamo eseguire operazioni su ogni elemento con un solo comando.<BR>

In [30]:
x = np.arange(0, 2, 0.5)
print(x)

[0.  0.5 1.  1.5]


In [31]:
print(x + 10)
print(x*33)
print(x ** 2)

[10.  10.5 11.  11.5]
[ 0.  16.5 33.  49.5]
[0.   0.25 1.   2.25]


La maggior parte delle operazioni (`+`, `-`, `*`, `/`) agiscono su tutto un array in un solo colpo, elemento per elemento.

In [32]:
y1 = np.array([1.,2.,3.])
y2 = np.array([-1.,-10,+100])
y1+y2

array([  0.,  -8., 103.])

Nel modulo numpy sono definite tutte le funzioni matematiche più comuni in modo che agiscano su tutti gli elementi di un array. Sono definite anche le costanti come np.e e np.pi. In generale è superfluo importare separatamente il modulo math.

In [33]:
print(np.sin(x))
print(np.e)

[0.         0.47942554 0.84147098 0.99749499]
2.718281828459045


La funzione `mod` corrisponde alla operazione modulo `%` con molte opzioni in più (Hint: help(np.mod)).

In [34]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
np.mod(x,6)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3], dtype=int32)

Il modo migliore di utilizzare una funzione in numpy è definire l'array dei punti in cui la funzione deve essere calcolata e poi applicare la funzione all'array.<BR>
Esempio: per calcolare i valori del polinomio y = 3\* x\*\*3 - 2\*x\*\*2 + 1 fra -5 e 5:

In [36]:
def myfunc(arr):
    return 3*arr**3 -2*arr*arr +1

x = np.linspace(-5,5,101)
print(x)
res = myfunc(x)
res

[-5.  -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7
 -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
 -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9
 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5
  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3
  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7
  4.8  4.9  5. ]


array([-4.24000e+02, -3.99967e+02, -3.76856e+02, -3.54649e+02,
       -3.33328e+02, -3.12875e+02, -2.93272e+02, -2.74501e+02,
       -2.56544e+02, -2.39383e+02, -2.23000e+02, -2.07377e+02,
       -1.92496e+02, -1.78339e+02, -1.64888e+02, -1.52125e+02,
       -1.40032e+02, -1.28591e+02, -1.17784e+02, -1.07593e+02,
       -9.80000e+01, -8.89870e+01, -8.05360e+01, -7.26290e+01,
       -6.52480e+01, -5.83750e+01, -5.19920e+01, -4.60810e+01,
       -4.06240e+01, -3.56030e+01, -3.10000e+01, -2.67970e+01,
       -2.29760e+01, -1.95190e+01, -1.64080e+01, -1.36250e+01,
       -1.11520e+01, -8.97100e+00, -7.06400e+00, -5.41300e+00,
       -4.00000e+00, -2.80700e+00, -1.81600e+00, -1.00900e+00,
       -3.68000e-01,  1.25000e-01,  4.88000e-01,  7.39000e-01,
        8.96000e-01,  9.77000e-01,  1.00000e+00,  9.83000e-01,
        9.44000e-01,  9.01000e-01,  8.72000e-01,  8.75000e-01,
        9.28000e-01,  1.04900e+00,  1.25600e+00,  1.56700e+00,
        2.00000e+00,  2.57300e+00,  3.30400e+00,  4.211

check:

In [37]:
3*(-4.9)**3 -2*(-4.9)**2 +1.

-399.9670000000001

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#ff0000; margin:20px 0px 10px 10px">
    <h4> Attenzione!</h4>
    È sbagliato e dannoso iterare esplicitamente, per esempio usando un `for` loop, sulle componenti di un array.
</div>

- Come estrarre più elementi da un array

In [38]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
x1 = [x[2],x[3],x[5]]
print(x1)
type(x1)

[7, 8, 10]


list

Per ottenere un array dal risultato precedente:

In [40]:
x1 = np.array(x1)
print(x1)
type(x1)

[ 7  8 10]


numpy.ndarray

- Come estrarre più elementi da un array usando un array di indici

In [41]:
ind = [2,3,5]
x[ind]       # Restituisce un array

array([ 7,  8, 10])

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
    
<OL>
<LI>Create un array A di 10 elementi uguali a -2.
<LI>Create un array B di 21 elementi equidistanziati fra -np.pi e np.pi.
<LI>Create un array C aggiungendo np.pi a tutii gli elementi di B.
<LI>Invertite l'ordine degli elementi di C.
<LI>Create un array D di elementi distanziati di 0.15 fra -2 e 1 in modo che 1 sia incluso.
<LI>Estraete il terzultimo elemento di D.
<LI>Create l'array E del quadrato degli elementi di D.
<LI>Calcolate la differenza, elemento per elemento, fra E e D.
<LI>Calcolate il valore di <b>sin(2*x)</b> in 201 punti <b>x</b> equidistanziati fra 0 e np.pi  
<LI>Costruite una funzione <b>parabola(a,b,c,xmin,xmax,npoints)</b> che restutuisca un array di <b>npoints</b> valori di <b>y</b>
    in <b>npoints</b> punti <b>x</b> equidistanziati fra
    <b>xmin</b> e <b>xmax</b> (compresi) appartenenti alla parabola <b>y = a*x**2 + b*x + c</b>.
</OL>
</div>

In [49]:
#1
import numpy as np
A = np.ones(10)*-2
print(A)

[-2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]


In [55]:
#2
import numpy as np
B = np.linspace(-np.pi, np.pi , 21)
print(B)

[-3.14159265 -2.82743339 -2.51327412 -2.19911486 -1.88495559 -1.57079633
 -1.25663706 -0.9424778  -0.62831853 -0.31415927  0.          0.31415927
  0.62831853  0.9424778   1.25663706  1.57079633  1.88495559  2.19911486
  2.51327412  2.82743339  3.14159265]


In [57]:
#3
import numpy as np
C = np.zeros(10)
C += np.pi
print(C)

[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265 3.14159265
 3.14159265 3.14159265 3.14159265 3.14159265]


In [59]:
#4
import numpy as np
print(B[::-1])

[ 3.14159265  2.82743339  2.51327412  2.19911486  1.88495559  1.57079633
  1.25663706  0.9424778   0.62831853  0.31415927  0.         -0.31415927
 -0.62831853 -0.9424778  -1.25663706 -1.57079633 -1.88495559 -2.19911486
 -2.51327412 -2.82743339 -3.14159265]


In [70]:
#5
import numpy as np
D = np.arange(-2,1.01,0.15)
print(D)
#6
D[-3]
#7
E = D**2
print(E)
#8
print(E-D)

[-2.   -1.85 -1.7  -1.55 -1.4  -1.25 -1.1  -0.95 -0.8  -0.65 -0.5  -0.35
 -0.2  -0.05  0.1   0.25  0.4   0.55  0.7   0.85  1.  ]
[4.0000e+00 3.4225e+00 2.8900e+00 2.4025e+00 1.9600e+00 1.5625e+00
 1.2100e+00 9.0250e-01 6.4000e-01 4.2250e-01 2.5000e-01 1.2250e-01
 4.0000e-02 2.5000e-03 1.0000e-02 6.2500e-02 1.6000e-01 3.0250e-01
 4.9000e-01 7.2250e-01 1.0000e+00]
[ 6.00000000e+00  5.27250000e+00  4.59000000e+00  3.95250000e+00
  3.36000000e+00  2.81250000e+00  2.31000000e+00  1.85250000e+00
  1.44000000e+00  1.07250000e+00  7.50000000e-01  4.72500000e-01
  2.40000000e-01  5.25000000e-02 -9.00000000e-02 -1.87500000e-01
 -2.40000000e-01 -2.47500000e-01 -2.10000000e-01 -1.27500000e-01
 -1.77635684e-15]


In [75]:
#9
import numpy as np
x = np.linspace(0,np.pi,201)
np.sin(2*x)

array([ 0.00000000e+00,  3.14107591e-02,  6.27905195e-02,  9.41083133e-02,
        1.25333234e-01,  1.56434465e-01,  1.87381315e-01,  2.18143241e-01,
        2.48689887e-01,  2.78991106e-01,  3.09016994e-01,  3.38737920e-01,
        3.68124553e-01,  3.97147891e-01,  4.25779292e-01,  4.53990500e-01,
        4.81753674e-01,  5.09041416e-01,  5.35826795e-01,  5.62083378e-01,
        5.87785252e-01,  6.12907054e-01,  6.37423990e-01,  6.61311865e-01,
        6.84547106e-01,  7.07106781e-01,  7.28968627e-01,  7.50111070e-01,
        7.70513243e-01,  7.90155012e-01,  8.09016994e-01,  8.27080574e-01,
        8.44327926e-01,  8.60742027e-01,  8.76306680e-01,  8.91006524e-01,
        9.04827052e-01,  9.17754626e-01,  9.29776486e-01,  9.40880769e-01,
        9.51056516e-01,  9.60293686e-01,  9.68583161e-01,  9.75916762e-01,
        9.82287251e-01,  9.87688341e-01,  9.92114701e-01,  9.95561965e-01,
        9.98026728e-01,  9.99506560e-01,  1.00000000e+00,  9.99506560e-01,
        9.98026728e-01,  

In [78]:
import numpy as np

def parabola(a,b,c,xmin,xmax,npoints):
    x = np.linspace(xmin,xmax,npoints)
    punti = a*(x**2) + b*x + c
    return punti

parabola(1,2,1,-5,5,100)

array([1.60000000e+01, 1.52021222e+01, 1.44246505e+01, 1.36675849e+01,
       1.29309254e+01, 1.22146720e+01, 1.15188246e+01, 1.08433833e+01,
       1.01883481e+01, 9.55371901e+00, 8.93949597e+00, 8.34567901e+00,
       7.77226814e+00, 7.21926334e+00, 6.68666463e+00, 6.17447199e+00,
       5.68268544e+00, 5.21130497e+00, 4.76033058e+00, 4.32976227e+00,
       3.91960004e+00, 3.52984389e+00, 3.16049383e+00, 2.81154984e+00,
       2.48301194e+00, 2.17488011e+00, 1.88715437e+00, 1.61983471e+00,
       1.37292113e+00, 1.14641363e+00, 9.40312213e-01, 7.54616876e-01,
       5.89327620e-01, 4.44444444e-01, 3.19967350e-01, 2.15896337e-01,
       1.32231405e-01, 6.89725538e-02, 2.61197837e-02, 3.67309458e-03,
       1.63248648e-03, 1.99979594e-02, 5.87695133e-02, 1.17947148e-01,
       1.97530864e-01, 2.97520661e-01, 4.17916539e-01, 5.58718498e-01,
       7.19926538e-01, 9.01540659e-01, 1.10356086e+00, 1.32598714e+00,
       1.56881951e+00, 1.83205795e+00, 2.11570248e+00, 2.41975309e+00,
      

- Come estrarre da un array gli elementi che soddisfano una condizione data. Nell'esempio gli elementi dispari. 

In [88]:
arr = np.array([2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([3, 5, 7, 9])

oppure, con più flessibilità sul modo di imporre le condizioni:

In [80]:
np.array([x for x in arr if x% 2 == 1])

array([3, 5, 7, 9])

- Come sostituire in un array gli elementi che soddisfano una condizione data con un valore fisso.

In [82]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

- Come ottenere lo stesso risultato senza modificare l'array iniziale. `np.where(condition,X,Y)` restituisce l'elemento di `X` se la condizione è vera e l'elemento di `Y` se la condizione è falsa.

In [ ]:
#help(np.where)

In [83]:
arr = np.arange(2,10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
out

[2 3 4 5 6 7 8 9]


array([ 2, -1,  4, -1,  6, -1,  8, -1])

`np.where(condition)` restituisce una ntupla il cui primo elemento è l'array degli *indici* degli elementi per cui la condizione è vera.

In [90]:
out = np.where(arr % 2 == 1)
out

(array([1, 3, 5, 7], dtype=int64),)

Per estrarre i corrispondenti elementi:

In [89]:
arr[out]

array([3, 5, 7, 9])

Per imporre più condizioni si può utilizzare la notazione:

In [95]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where( (arr>=1) & (arr<+7) )

(array([1, 2, 3, 4, 5, 6], dtype=int64),)

Le parentesi tonde attorno alle condizioni sono indispensabili perchè l'operatore `&` ha precedenza più alta degli operatori di confronto. Le parentesi forzano Python a valutare le disuguaglianze prima di combinarle con `and`.

Si possono anche combinare le varie condizioni in una condizione unica con `logical_and`:

In [96]:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

NameError: name 'a' is not defined

- Come estrarre gli elementi "unici" e il numero di volte in cui compaiono in un array:

In [97]:
uniqs, counts = np.unique(out, return_counts=True)
print("Unique items : ", uniqs)

Unique items :  [1 3 5 7]


In [98]:
uniqs2 = np.unique(out)
uniqs2

array([1, 3, 5, 7], dtype=int64)

In [ ]:
#help(np.unique)

- Come selezionare gli elementi comuni fra due array.

In [99]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

- Come eliminare da un array `a` tutti gli elementi che compaiono anche in `b`.

In [100]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [101]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [102]:
np.asarray(a == b)

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

In [103]:
np.asarray(a == b).nonzero()     # restituisce gli indici degli elementi non nulli cioè di quelli non False

(array([1, 3, 5, 7], dtype=int64),)

- Come ordinare un array.

Python ha il metodo `sort` e la funzione `sorted` per ordinare liste. In numpy si può usare la funzione `numpy.sort` che restituisce una copia ordinata dell'array passato in input.

In [104]:
x = np.array([1,3,2])
y = np.sort(x)
print(y)

[1 2 3]


Per ordinare un array in ordine decrescente una possibilità è:

In [105]:
y1 = np.sort(x)[::-1]
print(y1)

[3 2 1]


### 7.2.3 Convertire da  array a lista o tuple

Per convertire un array in una lista o una si possono usare le funzioni python standard <span>`list(s0)`</span> e <span>`tuple(s0)`</span> che accettano una sequenza <span>`s0`</span> come input e ritornano rispettivamente  una lista e una ntupla:

In [106]:
a = np.array([1, 4, 10])
a

array([ 1,  4, 10])

In [107]:
list(a)

[1, 4, 10]

In [109]:
tuple(a)

(1, 4, 10)

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
    
<OL>
<LI>Dall'array A = np.arange(20, 101) estrarre l'array dei multipli di 13.
<LI>Dall'array B = np.cos(np.linspace(0,np.pi,100)) estarre gli elementi di valore compreso fra -0.1 e 0.3.
<LI>Dall'array C = np.arange(-4., 2.,0.3) estrarre gli elementi il cui quadrato sia compreso fra 1 e 4.
<LI>Dall'array D = np.array(['a','b','a','e','e','a']) estrarre gli elementi unici e le corrispondenti molteplicità.
<LI>Estrate gli elementi comuni fra gli array E = np.arange(2.,10.,0.2) e F = np.arange(-1.,7.,0.4).
</OL>
</div>

In [125]:
A = np.arange(20, 101)
a = np.array([i for i in A if i%13==0])
#  -->   A[A%13==0]
print(a)

[26 39 52 65 78 91]


In [133]:
B = np.cos(np.linspace(0,np.pi,100))
B[(-0.1<=B) & (B<=0.3)]
#  a = np.array([i for i in B if i>=-0.1 and i<=0.3])
#  print(a)

array([ 0.29692038,  0.26647381,  0.23575894,  0.20480667,  0.17364818,
        0.14231484,  0.1108382 ,  0.07924996,  0.04758192,  0.01586596,
       -0.01586596, -0.04758192, -0.07924996])

In [137]:
C = np.arange(-4., 2.,0.3)
C[(1<=C**2) & (C**2<=4)]
#  a = np.array([i for i in C if i**2>=1 and i**2<=4])
#  print(a)

array([-1.9, -1.6, -1.3, -1. ,  1.1,  1.4,  1.7])

In [141]:
D = np.array(['a','b','a','e','e','a'])
np.unique(D, return_counts=True)

(array(['a', 'b', 'e'], dtype='<U1'), array([3, 1, 2], dtype=int64))

In [147]:
E = np.arange(2.,10.,0.2)
F = np.arange(-1.,7.,0.4)
a = np.intersect1d(E,F)
print(a)

[2.2]


<div style= 'padding:20px 20px 0px 150px;'>
    <img src="../Humour/hip-hip-array.jpg" width="500" align="center"/>
</div>

### 7.2.4  %timeit per valutare il tempo di esecuzione di un comando
È spesso utile misurare il tempo necessario per eseguire dei comandi. Jupyter fornisce la funzione %timeit che possiamo utilizzare per mostrare la maggiore velocità delle operazioni di Numpy su array rispetto alle operazioni di math su liste.

In [110]:
def forloopmethod(N):
    a1 = [0]*N
    for i in range(N):
        a1[i] = float(i)**2  # passare a numeri reali rende l'operazione più veloce 
    return sum(a1)

def numpymethod(N):
    a3 = np.sum(np.arange(0, N)**2, dtype='d')  # dtype = 'd' vuol dire double precision
    return a3

In [111]:
N = 1000000

%timeit forloopmethod(N)
%timeit numpymethod(N)

206 ms ± 4.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
3.2 ms ± 145 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


###  7.2.5 Matrici (2d-arrays)

Ecco due modi per creare un array a due dimensioni:

-   Convertendo una lista di liste (o tuples) in un array (Ciascuna sottolista corrisponde a una riga della matrice):

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

-  Usare il metodo  <span>`zeros`</span> (<span>`ones`</span>) per creare una matrice di zeri (uno). Un esempio con 5 righe e 4 colonne:

In [4]:
x = np.zeros((5, 4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

La "forma" di una matrice può essere trovata con il comando `shape` (in questo caso ci sono 2 righe e 3 colonne):

In [5]:
x=np.array([[1, 2, 3], [4, 5, 6]])
print(x)
x.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

La "forma" di una matrice può essere modificata con il comando/metodo `reshape`:

In [8]:
a = np.arange(6).reshape((3, 2)) # metodo
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
np.reshape(a, (2, 3)) # funzione

array([[0, 1, 2],
       [3, 4, 5]])

I singoli elementi possono essere recuperati con la sintassi seguente:

In [9]:
x=np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
x[0, 0]

1

In [10]:
x[0, 1]

2

In [11]:
x[0, 2]

3

In [12]:
x[1, 0]

4

Per recuperare una riga o una colonna:

In [13]:
x[:, 0]

array([1, 4, 7])

In [ ]:
x[0,:]

Per recuperare una lista di righe o colonne:

In [16]:
x[[0,1],:]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
x[np.arange(1,3),:]

array([[4, 5, 6],
       [7, 8, 9]])

La stessa sintassi si utilizza per modificare un elemento della matrice:

In [18]:
x[1,0] = 157
x

array([[  1,   2,   3],
       [157,   5,   6],
       [  7,   8,   9]])

- Un esempio su come sostituire elementi multipli in una matrice<BR>
Supponiamo di voler creare la matrice:
 $$A = \begin{bmatrix} -2 & 0 & 0 \\ 0 & 5 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$
 Un metodo è il seguente:  

In [21]:
A = np.zeros((3,3))
print(A)
vec = np.array([-2,5,1])
indices = np.array([0,1,2])
A[indices,indices] = vec
A

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[-2.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0.,  1.]])

Un esempio che utilizza due array diversi per gli indici sulle righe e gli indici sulle colonne:

In [22]:
A = np.zeros((4,4))
ind_row = np.array([0,2])
ind_col = np.array([1,3])
vec1  = np.array([5,1])
A[ind_row,ind_col] = vec1
A

array([[0., 5., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
    
<OL>
<LI>Costruite la matrice
    $$
A = \left( \begin{matrix}
1 & 2  \\
3 & 4  \\ 
\end{matrix} \right).
$$
Estrate da $A$, in forma di array, la prima colonna, la seconda, la prima riga, la seconda.
<LI>Create una matrice A con 4 righe e due colonne i cui elementi siano uguali a -2.
<LI>In A sostituite tutti gli elementi della seconda riga con 33.
<LI>Create un array B di numeri interi fra 1 e 18. Trasformate B in un array di <b>shape</b>  (9,2), (2,9), (6,3).<BR>
    Perchè non è possibile trasformare A in un array di <b>shape</b> (5,4)?
</OL>
</div>

In [46]:
A = np.array([[1,2],[3,4]])
print(A,"\n")

"""c1 = np.array(A[:,0])
print(c1)
c2 = np.array(A[:,1])
print(c2)
r1 = np.array(A[0,:])
print(r1)
r2 = np.array(A[1,:])
print(r2)"""

D = np.ones((4,2))*(-2)
D[1,:]=33
print(D,"\n")

B = np.arange(1,19)
print(B,"\n")

print(B.reshape(9,2),"\n")
print(B.reshape(2,9),"\n")
print(B.reshape(6,3),"\n")

[[1 2]
 [3 4]] 

[[-2. -2.]
 [33. 33.]
 [-2. -2.]
 [-2. -2.]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18] 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]] 

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]] 



### 7.2.6 Operazioni standard in Algebra Lineare

#### Vettori

Prodotto interno (scalare), esterno, vettoriale

In [47]:
x = np.array([1, 4, 0], float)
y = np.array([2, 2, 1], float)
print("Matrices and vectors.")
print("x:")
print(x)
print("y:")
print(y)

Matrices and vectors.
x:
[1. 4. 0.]
y:
[2. 2. 1.]


In [48]:
print("Inner product of x and y:")   #prodotto scalare 
print(np.inner(x, y))

Inner product of x and y:
10.0


In [49]:
print("Outer product of x and y:")   #prodotto diadico o prodotto esterno
print(np.outer(x, y))

Outer product of x and y:
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]


In [50]:
print("Cross product of x and y:")  #prodotto vettoriale 
print(np.cross(x, y))

Cross product of x and y:
[ 4. -1. -6.]


#### Moltiplicazione fra matrici

Due arrays possono essere moltiplicato nel senso usuale dell'algebra lineare usando <span>`numpy.dot`</span>. Ecco un esempio:

In [55]:
import numpy as np
import numpy.random       
A = numpy.random.rand(5, 5)    # genera matrice random 5 by 5 
x = numpy.random.rand(5)       # genera un vettore di 5 elementi
print(A)

[[0.60547479 0.14575874 0.34067435 0.04549514 0.51769689]
 [0.19660763 0.36476761 0.19773516 0.56613179 0.2346889 ]
 [0.09204585 0.74172484 0.37549948 0.39996047 0.25386305]
 [0.22100613 0.459931   0.8212802  0.06146403 0.11948862]
 [0.8224886  0.25243151 0.69897292 0.81823678 0.6720822 ]]


In [56]:
print(x)

[0.45935032 0.55156443 0.80023576 0.23330221 0.56291725]


In [61]:
b=np.dot(A, x)                  # multiplica la matrice A per il vettore x 
print(b)

[0.93317481 0.71392959 0.98809399 1.09402051 1.64560888]


#### Risolvere un sistema di  equazioni lineari

Per risolvere un sistema di  equazioni lineari `A*x = b`, dato in forma matriciale (cioè `A` è una matrice e `x` e `b` sono vettori, con `A` e `b` noti), possiamo usare la libreria di algebra lineare <span>`linalg`</span> di <span>`numpy`</span>:

In [62]:
import numpy.linalg as LA
x = LA.solve(A, b)
x

array([0.45935032, 0.55156443, 0.80023576, 0.23330221, 0.56291725])

check:

In [63]:
print(np.dot(A,x))
print(b)

[0.93317481 0.71392959 0.98809399 1.09402051 1.64560888]
[0.93317481 0.71392959 0.98809399 1.09402051 1.64560888]


#### Determinante e traccia

In [64]:
X = np.array([[1, 2], [4, 5]])

In [65]:
LA.det(X)

-2.9999999999999996

In [66]:
np.trace(X)

6

In [ ]:
#help(np.linalg)

#### Matrice inversa e trasposta

In [67]:
X = np.array([[1, 2], [4, 5]])
Xinv = LA.inv(X)
print(Xinv)
np.dot(X,Xinv)

[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


array([[1., 0.],
       [0., 1.]])

In [68]:
Xt = np.transpose(X)
print(Xt)

[[1 4]
 [2 5]]


#### Calcolare autovettori e autovalori (eigenvector e eigenvalue)

Ricordiamo che data una matrice $M$, il vettore non nullo $v_i$ è un autovettore di $M$ e lo scalare $\lambda_i$
è il corrispondente autovalore se:
$$ M\,v_i = \lambda_i \, v_i.$$
Ecco un piccolo esempio che calcola gli autovettori e autovalori di una matrice con il comando <span>`eig`</span>:

In [69]:
import numpy.linalg as LA
import numpy as np

R = np.array([[1,2,3], [1,0,1], [0,1,2]])

In [70]:
LA.det(R)

-2.0

In [71]:
evalues, evectors = LA.eig(R)

In [72]:
print(evalues)

[-0.86080585  0.74589831  3.11490754]


Controlliamo se il prodotto degli autovalori è uguale al determinante:

In [73]:
np.prod(evalues)

-1.9999999999999987

In [74]:
print(evectors)

[[ 0.43464691  0.7699547   0.85535358]
 [-0.85015846  0.49890739  0.38564667]
 [ 0.29717447 -0.39782052  0.34590013]]


**Attenzione:** gli autovettori sono disposti sulle **colonne**.<BR>
    Verifica:

In [75]:
A1=evectors[:,0]
print(A1)

[ 0.43464691 -0.85015846  0.29717447]


In [76]:
print(np.dot(R,A1))

[-0.3741466   0.73182138 -0.25580952]


In [77]:
print(evalues[0]*A1)

[-0.3741466   0.73182138 -0.25580952]


Ciascuno di questi comandi fornisce la propria documentazione. Per esempio, <span>`help(LA.eig)`</span> fornisce dettagli sulla funzione che calcola autovettori e autovalori (Avendo importato `numpy.linalg` come `LA`).

#### Ordinare gli elementi di una matrice

In [78]:
X = np.array(
[[6, 3, 7],
 [2, 6, 4],
 [7, 2, 5]] 
)

Ordinare le colonne:

In [79]:
np.sort(X, axis=0)

array([[2, 2, 4],
       [6, 3, 5],
       [7, 6, 7]])

Ordinare le righe:

In [80]:
np.sort(X, axis=1)

array([[3, 6, 7],
       [2, 4, 6],
       [2, 5, 7]])

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
    
<OL>
<LI>Calcolate la lunghezza del vettore A = np.array([0.3,-1.7,0.8]) usando il prodotto scalare.
<LI>Determinate se la matrice B = np.array([[0,3,1],[-1,2,0],[1,1,3]]) è invertibile.
<LI>Cercate nella documentazione di <b>numpy</b> come calcolare l'inverso di una matrice. Se possibile, calcolate la matrice inversa di B.
<LI>Per ruotare un vettore (colonna) di un angolo <b>theta</b> è sufficiente moltiplicarlo per la matrice 
    <b>R(theta) = [[cos(theta),-sin(theta)],[sin(theta),cos(theta)]]</b>.
    Costruite una funzione <b>rot(v,theta)</b> che dato un vettore reale di lunghezza 2 restituisca il vettore ruotato di
    <b>theta</b>. Testate la funzione con <b>v = np.array([1,1])</b> e <b>theta = pi/2</b>.
</OL>
</div>

In [31]:
import numpy as np
import numpy.linalg as LA

A = np.array([0.3,-1.7,0.8])
B = np.array([[0,3,1],[-1,2,0],[1,1,3]]) 
Norm = np.sqrt(np.inner(A,A))
print(Norm)

if LA.det(B)!=0: 
    print("\nLa matrice è invertibile:")
    InvB = LA.inv(B)
    print(InvB)
else: 
    print("\nLa matrice non è invertibile\n")

def rot(v,theta):
    if len(v) == 2: 
        R = [[np.cos(theta),-np.sin(theta)],[np.sin(theta),np.cos(theta)]]
        v = v*R
    else: 
        print("Il vettore deve avere lunghezza 2")
    return v

v = np.array([1,1])
theta = np.pi/2

print("\n")
rot(v,theta)

1.9026297590440446

La matrice è invertibile:
[[ 1.         -1.33333333 -0.33333333]
 [ 0.5        -0.16666667 -0.16666667]
 [-0.5         0.5         0.5       ]]




array([[ 6.123234e-17, -1.000000e+00],
       [ 1.000000e+00,  6.123234e-17]])

### 7.2.7 Come vettorializzare una funzione

Per avere programmi veloci è necessario evitare di ciclare sugli elementi di vettori e matrici usando invece algoritmi vettorializzati. Il primo passo per convertire un algoritmo scalare in un algoritmo vettorializzato è costruire delle funzioni che accettino input vettoriali.
<BR>
AVVERTENZA: è quasi sempre possibile trovare funzioni di Numpy, quindi già vettorializzate, che facciano quello che ci serve. `vectorize` va utilizzata come ultima risorsa quando tutte le ricerche nella documentazione e in rete si sono rivelate vane. 

In [81]:
def Theta(x):
    """
    Implemenazione scalare della funzione a gradino di Heaviside.
    """
    if x >= 0:
        return 1
    else:
        return 0
    
Theta(0.3)

1

Se passiamo a `Theta` un array o qualunque altro oggetto iterabile otteniamo un errore:

In [82]:
Theta((1,2))

TypeError: '>=' not supported between instances of 'tuple' and 'int'

In [83]:
Theta(np.array([-3,-2,-1,0,1,2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Per ottenere una versione vettorializzata di Theta si può utilizzare la  funzione  di Numpy `vectorize`. In molti  casi `vectorize` riesce a creare una funzione vettoriale che opera come la funzione scalare ma su tutti gli elementi di qualunque array:

In [84]:
Theta_vec = np.vectorize(Theta) # Theta_vec è una funzione diversa da Theta

In [85]:
Theta_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

### Copia shallow e copia deep di array numpy

In [3]:
import numpy as np
a = np.array([1,2,3])
b = a
a[2] = 22

In [4]:
print(b)

[ 1  2 22]


La copia con [:] non è sufficiente a creare una deep copy

In [5]:
a = np.array([1,2,3])
b = a[:]
a[2] = 22

In [6]:
print(b)

[ 1  2 22]


Bisogna usare la funzione deepcopy nlla libreria `copy`.

In [7]:
import copy
a = np.array([1,2,3])
b = copy.deepcopy(a)
a[2] = 22

In [8]:
print(b)

[1 2 3]


### 7.2.8 Array multidimensionali
Tipicamente le funzioni di numpy possono operare su array multidimensionali. È quindi necessario poter controllare come la funzione agisce sull'array. Un caso tipico è far operare la funzione lungo un singolo asse (axis) dell'array. Un semplice esempio usando la funzione `sum`.

In [9]:
np.sum([[0, 1], [3, 5]])

9

In [93]:
np.sum([[0, 1], [3, 5]], axis=0)

array([3, 6])

In [10]:
np.sum([[0, 1], [3, 5]], axis=1)

array([1, 8])

### 7.2.9 Come importare dentro degli array i dati contenuti in un file di testo

Quando si debba trattare una grande massa di dati è essenziale poterli importare ed esportare su file in modo veloce.
 
Numpy fornisce la funzione `loadtxt`:

In [11]:
import numpy as np

dataPt, time, height, error = np.loadtxt( "../Data/CadutaLiberaDati.txt", skiprows=5 , unpack=True)

Il parametro `skiprows=5` dice a `loadtxt` di ignorare le prime cinque righe che costituiscono l'`header` del file. Il parametro `unpack=True` dice di estrarre i dati caricandoli nell'ntupla di array a primo membro. Il comando assume che i dati siano separati da uno o più spazi.

In [96]:
print(height)

[502.1  497.9  490.33 479.05 461.22 439.28 411.13 379.04 341.98 302.84
 252.72 204.29 147.57  85.52  19.62]


Se i dati sono contenuti in un Comma-Separated Values file (CSV), una alternativa molto comune, è sufficiente specificare il separatore con la keyword `delimiter`.

In [97]:
dataPt, time, height, error = np.loadtxt("../Data/CadutaLiberaDati.csv", skiprows=5 , unpack=True, delimiter=',')

Si possono importare da un file con dati testuali e numerici usando `dtype=str`. In questo caso i dati sono rappresentati come stringhe.

In [98]:
gender, weight, age = np.loadtxt("../Data/mixed_data.txt", skiprows=2 , unpack=True, dtype=str)
print(gender)
print(weight)
print(age)

['F' 'M']
['50' '78']
['37' '41']


È poi possibile convertire parte degli array in un formato numerico usando il metodo `astype`:

In [99]:
age_n = age.astype(float)
print(age_n)

[37. 41.]


Esistono metodi ancora più raffinati come genfromtxt. Usate help(np.genfromtxt) oppure una ricerca sul web per ulteriori dettagli ed esempi

In [13]:
import numpy as np
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [12]:
np.genfromtxt("../Data/mixed_data.txt", skip_header=2 , dtype=None, encoding=None,
              names=('gender', 'weight', 'age'))

array([('F', 50, 37), ('M', 78, 41)],
      dtype=[('gender', '<U1'), ('weight', '<i4'), ('age', '<i4')])

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
<OL>
<LI>Esaminate con un editor di testo o facendolo stampare in una finestra di comandi il contenuto del file "../Data/Iris_Dataset.csv".
<LI>Leggete dal file "../Data/Iris_Dataset.csv" le cinque colonne di dati usando il metodo <b>loadtxt</b>.
<OL>
    <LI>Determinate il numero di dati con sepal.width compresi fra 6.2 cm e 7.3 cm.
    <LI>Determinare quante misurazioni si riferiscono ad esemplari della varietà "Versicolor".
</OL>
</OL>
</div>

In [147]:
with open('../Data/Iris_Dataset.csv', "r") as f: 
    print(f.read())

"sepal.length","sepal.width","petal.length","petal.width","variety"
5.1,3.5,1.4,.2,"Setosa"
4.9,3,1.4,.2,"Setosa"
4.7,3.2,1.3,.2,"Setosa"
4.6,3.1,1.5,.2,"Setosa"
5,3.6,1.4,.2,"Setosa"
5.4,3.9,1.7,.4,"Setosa"
4.6,3.4,1.4,.3,"Setosa"
5,3.4,1.5,.2,"Setosa"
4.4,2.9,1.4,.2,"Setosa"
4.9,3.1,1.5,.1,"Setosa"
5.4,3.7,1.5,.2,"Setosa"
4.8,3.4,1.6,.2,"Setosa"
4.8,3,1.4,.1,"Setosa"
4.3,3,1.1,.1,"Setosa"
5.8,4,1.2,.2,"Setosa"
5.7,4.4,1.5,.4,"Setosa"
5.4,3.9,1.3,.4,"Setosa"
5.1,3.5,1.4,.3,"Setosa"
5.7,3.8,1.7,.3,"Setosa"
5.1,3.8,1.5,.3,"Setosa"
5.4,3.4,1.7,.2,"Setosa"
5.1,3.7,1.5,.4,"Setosa"
4.6,3.6,1,.2,"Setosa"
5.1,3.3,1.7,.5,"Setosa"
4.8,3.4,1.9,.2,"Setosa"
5,3,1.6,.2,"Setosa"
5,3.4,1.6,.4,"Setosa"
5.2,3.5,1.5,.2,"Setosa"
5.2,3.4,1.4,.2,"Setosa"
4.7,3.2,1.6,.2,"Setosa"
4.8,3.1,1.6,.2,"Setosa"
5.4,3.4,1.5,.4,"Setosa"
5.2,4.1,1.5,.1,"Setosa"
5.5,4.2,1.4,.2,"Setosa"
4.9,3.1,1.5,.2,"Setosa"
5,3.2,1.2,.2,"Setosa"
5.5,3.5,1.3,.2,"Setosa"
4.9,3.6,1.4,.1,"Setosa"
4.4,3,1.3,.2,"Setosa"
5.1,3.4,1.5,.2,"Seto

In [210]:
a = np.loadtxt("../Data/Iris_Dataset.csv", dtype=str, max_rows=1, delimiter=',')

sepal_length, sepal_width, petal_length, petal_width, variety = np.loadtxt("../Data/Iris_Dataset.csv", skiprows=1 , unpack=True, dtype=str,  delimiter=',')

sepal_width = sepal_width.astype(float)

b = sepal_width[(sepal_width>=6.2) & (sepal_width<=7.3)]

print(f"Numero di dati con sepal.width compresi fra 6.2 cm e 7.3 cm è: {len(b)}")

c = len(variety[variety=='"Versicolor"'])

print(f"Il numero di misurazioni che si riferiscono alla varietà Versicolor è di {c}")

Numero di dati con sepal.width compresi fra 6.2 cm e 7.3 cm è: 0
Il numero di misurazioni che si riferiscono alla varietà Versicolor è di 50


In [210]:
a = np.loadtxt("../Data/Iris_Dataset.csv", dtype=str, max_rows=1, delimiter=',')

sepal_length, sepal_width, petal_length, petal_width, variety = np.loadtxt("../Data/Iris_Dataset.csv", skiprows=1 , unpack=True, dtype=str,  delimiter=',')

sepal_width = sepal_width.astype(float)

b = sepal_width[(sepal_width>=6.2) & (sepal_width<=7.3)]

print(f"Numero di dati con sepal.width compresi fra 6.2 cm e 7.3 cm è: {len(b)}")

c = len(variety[variety=='"Versicolor"'])

print(f"Il numero di misurazioni che si riferiscono alla varietà Versicolor è di {c}")

Numero di dati con sepal.width compresi fra 6.2 cm e 7.3 cm è: 0
Il numero di misurazioni che si riferiscono alla varietà Versicolor è di 50


### 7.2.10 Come esportare degli array in un file di testo

Esempio usando gli array importati in precedenza:

In [235]:
info = "Misure esperimento Caduta Libera\n"
info +="Data: 13 Dicembre 2019\n"
info +="\n\n"
info +="       Punto    Tempo(sec)   Altezza(m)   Incertezza(m)\n"

np.savetxt('../ShellPrograms/CLD.txt',
           list(zip(dataPt, time, height, error)),
           header=info, fmt="%12.1f")

Se si preferisce un file CSV:

In [ ]:
np.savetxt('../ShellPrograms/CLD.csv',
           list(zip(dataPt, time, height, error)),
           header=info, fmt="%12.1f", delimiter=",")

La funzione `zip`, partendo da due o più oggetti iterabili (stringhe, liste, ntuple) di uguale lunghezza, restituisce un iteratore che combina
il contenuto degli oggetti di partenza. Per ottenere il risultato finale in un colpo solo, invece che un elemento alla volta, si passa l'iteratore generato da `zip` al comando `list`.<BR>
Esempi:

In [100]:
l1 = [1,2,3]
l2 = ['a','b','c']
list(zip(l1,l2))

[(1, 'a'), (2, 'b'), (3, 'c')]

In [101]:
l1 = 'pippo'
l2 = 'pluto'
list(zip(l1,l2))

[('p', 'p'), ('i', 'l'), ('p', 'u'), ('p', 't'), ('o', 'o')]

In [102]:
l1 = [1,2,3,4,5]
l2 = 'pluto'
list(zip(l1,l2))

[(1, 'p'), (2, 'l'), (3, 'u'), (4, 't'), (5, 'o')]

<div style = "width:95%; padding:5px 10px 5px; border-style:solid; border-width:0px 0px 0px 10px; border-color:#b8d0d0; margin:20px 0px 10px 10px">
    <h4> Imparare Facendo</h4>
    
<OL>
<LI> Create un array di 100 righe e due colonne che contenga nella prima colonna i numeri interi fra 1 e 100 e nella seconda i corrispondenti quadrati.
<OL>
    <LI>salvate i risultati nel file <b>quadrati.txt</b> con header la data odierna e la stringa <code>  numeri    quadrati</code>.
    <LI>In una finestra di comandi fate stampare il contenuto di <b>quadrati.txt</b>.
</OL>
</OL>
</div>

In [266]:
x = np.zeros(200)
x = x.reshape(100,2)

w = np.arange(1,101)
y = np.array(w**2)

x[:,0]=w
#print(x)

x[:,1]=y
x = x.astype(int)
#print(x)

numeri = np.array(x[:,0])
quadrati = np.array(x[:,1])

#info="   |  Numeri  |  Quadrati  |"
info="Numeri"
info1="Quadrati"

np.savetxt('quadrati.txt',
           list(zip(numeri, quadrati)),
           header=f"|{info:>10}    | {info1:>10s}   |", fmt="%12.1f")
 
with open('quadrati.txt', "r") as f:
    print(f.read())

# |    Numeri    |   Quadrati   |
         1.0          1.0
         2.0          4.0
         3.0          9.0
         4.0         16.0
         5.0         25.0
         6.0         36.0
         7.0         49.0
         8.0         64.0
         9.0         81.0
        10.0        100.0
        11.0        121.0
        12.0        144.0
        13.0        169.0
        14.0        196.0
        15.0        225.0
        16.0        256.0
        17.0        289.0
        18.0        324.0
        19.0        361.0
        20.0        400.0
        21.0        441.0
        22.0        484.0
        23.0        529.0
        24.0        576.0
        25.0        625.0
        26.0        676.0
        27.0        729.0
        28.0        784.0
        29.0        841.0
        30.0        900.0
        31.0        961.0
        32.0       1024.0
        33.0       1089.0
        34.0       1156.0
        35.0       1225.0
        36.0       1296.0
        37.0       1369.0
    

### Ulteriori esempi per numpy …

…si possono trovare in: <http://www.scipy.org/Numpy_Example_List>