__Finiti gli esercizi, oppure il tempo a disposizione, salvate il notebook usando:__<BR>
```
File --> Save Notebook as
```
__usando il vostro cognome_nome come nome del file. Spedite il notebook, usando il vostro mailer preferito, a maina@to.infn.it, CON IL FILE IN ALLEGATO.__
    
Per determinare la cartella in cui il file viene salvato usate il comando `%pwd` in una cella a parte.

### Esercizio 1
__Costruite un array `myval` di 101 valori equidistanti fra $-\pi$ e $\pi$.
Costruite una funzione, `sin_sinsq(x)`, che restituisca l'array `s1` dei seni degli elementi di x e l'array `s2` dei seni al quadrato degli elementi di x. Testate la funzione con un piccolo array per cui potete verificare il risultato e poi su `myval`.__   

In [6]:
import numpy as np

def sin_sinsq(x):
    s1 = np.array(np.sin(x))
    s2 = np.array(np.sin(x)**2)
    return s1,s2

myval = np.linspace(-np.pi,np.pi,101)
x = np.array([0,np.pi/2,-np.pi/2,np.pi/6])

print(sin_sinsq(x),"\n")
print(sin_sinsq(myval),"\n")

(array([ 0. ,  1. , -1. ,  0.5]), array([0.  , 1.  , 1.  , 0.25])) 

(array([-1.22464680e-16, -6.27905195e-02, -1.25333234e-01, -1.87381315e-01,
       -2.48689887e-01, -3.09016994e-01, -3.68124553e-01, -4.25779292e-01,
       -4.81753674e-01, -5.35826795e-01, -5.87785252e-01, -6.37423990e-01,
       -6.84547106e-01, -7.28968627e-01, -7.70513243e-01, -8.09016994e-01,
       -8.44327926e-01, -8.76306680e-01, -9.04827052e-01, -9.29776486e-01,
       -9.51056516e-01, -9.68583161e-01, -9.82287251e-01, -9.92114701e-01,
       -9.98026728e-01, -1.00000000e+00, -9.98026728e-01, -9.92114701e-01,
       -9.82287251e-01, -9.68583161e-01, -9.51056516e-01, -9.29776486e-01,
       -9.04827052e-01, -8.76306680e-01, -8.44327926e-01, -8.09016994e-01,
       -7.70513243e-01, -7.28968627e-01, -6.84547106e-01, -6.37423990e-01,
       -5.87785252e-01, -5.35826795e-01, -4.81753674e-01, -4.25779292e-01,
       -3.68124553e-01, -3.09016994e-01, -2.48689887e-01, -1.87381315e-01,
       -1.25333234e-01, -6.279

In [4]:
import numpy as np

def sin_sinsq(x):
    s1 = np.sin(x)
    s2 = np.sin(x)**2
    return s1,s2

myval = np.linspace(-np.pi,np.pi,101)
x = np.array([0,np.pi/2,-np.pi/2,np.pi/6])

print(sin_sinsq(x),"\n")
print(sin_sinsq(myval),"\n")

(array([ 0. ,  1. , -1. ,  0.5]), array([0.  , 1.  , 1.  , 0.25])) 

(array([-1.22464680e-16, -6.27905195e-02, -1.25333234e-01, -1.87381315e-01,
       -2.48689887e-01, -3.09016994e-01, -3.68124553e-01, -4.25779292e-01,
       -4.81753674e-01, -5.35826795e-01, -5.87785252e-01, -6.37423990e-01,
       -6.84547106e-01, -7.28968627e-01, -7.70513243e-01, -8.09016994e-01,
       -8.44327926e-01, -8.76306680e-01, -9.04827052e-01, -9.29776486e-01,
       -9.51056516e-01, -9.68583161e-01, -9.82287251e-01, -9.92114701e-01,
       -9.98026728e-01, -1.00000000e+00, -9.98026728e-01, -9.92114701e-01,
       -9.82287251e-01, -9.68583161e-01, -9.51056516e-01, -9.29776486e-01,
       -9.04827052e-01, -8.76306680e-01, -8.44327926e-01, -8.09016994e-01,
       -7.70513243e-01, -7.28968627e-01, -6.84547106e-01, -6.37423990e-01,
       -5.87785252e-01, -5.35826795e-01, -4.81753674e-01, -4.25779292e-01,
       -3.68124553e-01, -3.09016994e-01, -2.48689887e-01, -1.87381315e-01,
       -1.25333234e-01, -6.279

### Esercizio 2
__Scrivete l'array `a1` dei numeri interi fra 10 e 270 incluso.  Estraete in un array `b2` gli elementi di `a1` che sono divisibili per 15. Costruite l'array `b3` invertendo l'ordine degli elementi di `b2`.
Costruite l'array `b4` dividendo l'array `b3` per l'array dei quadrati degli elementi di `b2`.__

In [5]:
import numpy as np

a1 = np.arange(10,271)
b2 = a1[a1%15==0]
print(b2,"\n")
b3 = b2[::-1]
print(b3,"\n")
b4 = b3/(b2**2)
print(b4)

[ 15  30  45  60  75  90 105 120 135 150 165 180 195 210 225 240 255 270] 

[270 255 240 225 210 195 180 165 150 135 120 105  90  75  60  45  30  15] 

[1.20000000e+00 2.83333333e-01 1.18518519e-01 6.25000000e-02
 3.73333333e-02 2.40740741e-02 1.63265306e-02 1.14583333e-02
 8.23045267e-03 6.00000000e-03 4.40771350e-03 3.24074074e-03
 2.36686391e-03 1.70068027e-03 1.18518519e-03 7.81250000e-04
 4.61361015e-04 2.05761317e-04]


### Esercizio 2
__Data la matrice:__
$$
R = \left( \begin{matrix}
1 & 3 & 1 & -1 \\
-1 & 2 & 2 & 0\\ 
0 & 2 & -1 & 1\\
-2 & 0 & 1 & -1\\
\end{matrix} \right)
$$

__Verificate che la matrice è invertibile. Calcolate la matrice inversa `Rinv` e usate `Rinv` per risolvere
i sistemi di equazioni lineari R\*X=B1 e R\*X=B2 con B1 = [3,1.5,2,-1.2] e B2 = [10,0.1,-2,1]. X è il vettore delle incognite.
Verificate che i risultati S1 e S2 soddisfano le equazioni R\*S1=B1 e R\*S2=B2__

In [61]:
import numpy as np
import numpy.linalg as LA

R = np.array([[1, 3, 1, -1],[-1, 2, 2, 0],[0, 2, -1, 1],[-2, 0, 1, -1]])

if LA.det(R) == 0: 
    print("La matrice non è invertibile")
elif LA.det(R)!=0: 
    print("La matrice è invertibile")
    Rinv = LA.inv(R)

    B1 = np.array([3 ,1.5 ,2 ,-1.2])
    B2 = np.array([10 ,0.1 ,-2 ,1])

    S1 = LA.solve(Rinv,B1)
    S2 = LA.solve(Rinv,B2)

    print("R*S1 =",LA.solve(R,S1))
    print("R*S2 =",LA.solve(R,S2))

La matrice è invertibile
R*S1 = [ 3.   1.5  2.  -1.2]
R*S2 = [10.   0.1 -2.   1. ]


### Esercizio 4
__Scrivete una funzione `ff(x,normalize=True)` che dato un array `x` restituisca l'array `x4` delle quarte potenze dei valori in `x`.  Se `normalize=True` `ff` Il vettore `x4` deve essere diviso per la somma dei suoi elementi__<BR>
__Testate `ff` su `np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3])` sia nel caso `normalize=True` che nel caso `normalize=False`.__

In [57]:
def ff(x,normalize=True): 
    x4 = x**4
    if normalize: 
        x4 = x4/sum(x4)
    return x4

x = np.array([-2,1,-0.1,4.2,0,1.2,-0.5,0.4,-1.3])

s1 = ff(x,normalize=True)
s2 = ff(x,normalize=False)
print(s1,"\n\n",s2)

[4.80210092e-02 3.00131307e-03 3.00131307e-07 9.33917389e-01
 0.00000000e+00 6.22352279e-03 1.87582067e-04 7.68336147e-05
 8.57205027e-03] 

 [1.600000e+01 1.000000e+00 1.000000e-04 3.111696e+02 0.000000e+00
 2.073600e+00 6.250000e-02 2.560000e-02 2.856100e+00]
